### ISSUE TITLE
recover_model_weight on reward-sim meet problem of _name_or_path and backbone_model_name_or_path

### ISSUE THREAD

**Issue by REIGN12** [tatsu-lab/alpaca_farm#28]
Really love your work on open sourcing the whole pipeline and all component!
But when I want to recover the model weight of reward-model-sim, I found this _name_or_path points to a absolute path
![image](https://github.com/tatsu-lab/alpaca_farm/assets/67776176/8f8b8233-0585-4598-876d-2b9cadad84cc)
And when I run the convert model weight, I encounter the following error
```
Traceback (most recent call last):
  File "/home/jingchu/RLHF/alpaca_farm/pretrained_models/recover_model_weights.py", line 89, in <module>
    model_tuned, tokenizer_tuned = load_weight_diff(hf_hub_name, is_reward_model, args.device)
  File "/home/jingchu/RLHF/alpaca_farm/pretrained_models/recover_model_weights.py", line 32, in load_weight_diff
    model_tuned = RewardModel.from_pretrained(
  File "/anaconda/envs/alpaca_farm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2611, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/jingchu/RLHF/alpaca_farm/src/alpaca_farm/models/reward_model.py", line 46, in __init__
    self.backbone_model = common.make_generative_lm(config.backbone_model_name_or_path, **kwargs)
  File "/home/jingchu/RLHF/alpaca_farm/src/alpaca_farm/common.py", line 120, in make_generative_lm
    return model_cls.from_pretrained(model_name_or_path, **kwargs)
  File "/anaconda/envs/alpaca_farm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2251, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/anaconda/envs/alpaca_farm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/anaconda/envs/alpaca_farm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/anaconda/envs/alpaca_farm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 650, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of '/juice5/scr5/nlp/crfm/human-feedback/models/selfinstruct/sft_v6_llama_7b_regen_v7_3ep'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/juice5/scr5/nlp/crfm/human-feedback/models/selfinstruct/sft_v6_llama_7b_regen_v7_3ep' is the correct path to a directory containing a config.json file
```
So what should I do to actually convert the model weight and what is the purpose of this _name_or_path? Many thanks!

**Comment by REIGN12** [comment]
I think for people easy to use your reward model, the following hack may save the day:
1. change the config.json in hf repo: change the backbone_name_or_path to any public llama weight(diff) huggingface repo
2. change the logic in common.py the function get_pretrained_model_name_with_model_name_or_path, to better handle this logic

Just some of my thoughts! Hope you guys may fix this bug soon! ❤️

**Comment by rtaori** [comment]
Ah sorry about this issue! Taking a look into it now

**Comment by rtaori** [comment]
Ok @REIGN12 I believe I have fixed the issue! Please look at the updated instructions at https://github.com/tatsu-lab/alpaca_farm#downloading-pre-tuned-alpacafarm-models.

In particular, first download the `sft10k` model, and afterwards downloading the reward models should work.
