### ISSUE TITLE
tried to use bnb, QLora on SFT but have errors

### ISSUE THREAD

**Issue by qiuruiyu** [tatsu-lab/alpaca_farm#63]
I tried to add bob, and qlora on set, so that I can use less computation resources to complete sft. 
I add `bnb_config`:
```python 
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )
```

```python 
peft_config = LoraConfig(
            lora_alpha=16,
            lora_dropout=0.1,
            r=64,
            target_modules=modules,
            bias="none",
            task_type="CAUSAL_LM",
        )
```

And also, **I update `transformers==4.31.0`**, script `sft.sh` metions that: 
```python 
 File "/usr/local/Miniconda3/envs/pytorch310/lib/python3.10/site-packages/torch/distributed/fsdp/flat_param.py", line 435, in _init_flat_param
    raise ValueError("Integer parameters are unsupported")
ValueError: Integer parameters are unsupported
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 40693) of binary: /usr/local/Miniconda3/envs/pytorch310/bin/python3.10
Traceback (most recent call last):
  File "/usr/local/Miniconda3/envs/pytorch310/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Miniconda3/envs/pytorch310/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/Miniconda3/envs/pytorch310/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/Miniconda3/envs/pytorch310/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/Miniconda3/envs/pytorch310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/Miniconda3/envs/pytorch310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

**Comment by lxuechen** [comment]
From what I understand, LoRA and torch native FSDP generally aren't compatible. 

What you see here is even to a further level since FSDP doesn't play nicely with quantization. 

If you're attempting to fine-tune with QLoRA, I believe their [official codebase](https://github.com/artidoro/qlora) might be a better reference.

**Comment by rtaori** [comment]
Closing this issue as there's no followup.

**Comment by qiuruiyu** [comment]
您好，感谢您的来信。已确认收到您的邮件，我会尽快处理您的邮件，谢谢。Hello！This is an automatic reply confirming that your email was received. Your email will be handled as soon as possible. Thank you！                                                      仇睿瑜                                              Joseph QIUThis is an automatic reply, confirming that your e-mail was received.Thank you
