### ISSUE TITLE
KeyError: 'llama' in /recover_model_weights.py

### ISSUE THREAD

**Issue by mensch72** [tatsu-lab/alpaca_farm#70]
[continuation of #69 ]
When trying `recover_model_weights.py` on llama-7b-hf as cloned from https://huggingface.co/decapoda-research/llama-7b-hf (following advice by lxuechen to look for copies of llama-7b on huggingface spaces), we (still) get the error 
```
Downloading sft10k
Traceback (most recent call last):
  File "/p/projects/ou/labs/gane/rlhf/git/alpaca_farm-collective/pretrained_models/recover_model_weights.py", line 112, in <module>
    model_tuned, tokenizer_tuned = load_weight_diff(hf_hub_name, is_reward_model, args.device, args.path_to_sft10k)
  File "/p/projects/ou/labs/gane/rlhf/git/alpaca_farm-collective/pretrained_models/recover_model_weights.py", line 48, in load_weight_diff
    model_tuned = transformers.AutoModelForCausalLM.from_pretrained(
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 873, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 579, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
```
Can you point us to any version of llama that should work, so that we can rule out that it is a problem with the model version?

**Comment by rtaori** [comment]
Which version of transformers was used when running the weights conversion script? We converted the raw llama weights into huggingface format using transformers==4.29.2 (as documented in the README)

**Comment by mensch72** [comment]
4.26.0, as required per requirements.txt. If I upgrade to 4.32.0, I get an even faster error:
```
Traceback (most recent call last):
  File "/p/projects/ou/labs/gane/rlhf/git/alpaca_farm-collective/pretrained_models/recover_model_weights.py", line 11, in <module>
    from alpaca_farm.models.reward_model import RewardConfig, RewardModel
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/alpaca_farm/models/reward_model.py", line 20, in <module>
    from .. import common
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/alpaca_farm/common.py", line 32, in <module>
    from transformers.trainer import WEIGHTS_NAME, is_deepspeed_zero3_enabled
ImportError: cannot import name 'is_deepspeed_zero3_enabled' from 'transformers.trainer' (/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/trainer.py)
```
