### ISSUE TITLE
Repeated Deprecation Error

### ISSUE THREAD

**Issue by syleedandekar** [tatsu-lab/alpaca_farm#87]
I am repeatedly getting this error when I try to run the pairwise annotator. How do I fix this? The problem seems to be from Alpaca Eval.

INFO:root:Sleeping 2 before retrying to call openai API...
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 404 Not Found"
WARNING:root:OpenAIError: Error code: 404 - {'error': {'message': 'The model text-davinci-003 has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}.
WARNING:root:Unknown error.
It's likely a rate limit so we are retrying...

Here is the full traceback:
Traceback (most recent call last):
File "/alpaca_farm/test_autoannotations.py", line 19, in
annotated = annotator.annotate_pairs(outputs_pairs)
File "/anaconda3/envs/llm-pref/lib/python3.10/site-packages/alpaca_eval/annotators/pairwise_evaluator.py", line 263, in annotate_pairs
return self.call(to_annotate, **decoding_kwargs)
File "/anaconda3/envs/llm-pref/lib/python3.10/site-packages/alpaca_eval/annotators/base.py", line 188, in call
df_annotated = self._annotate(curr_df_to_annotate, **decoding_kwargs)
File "/anaconda3/envs/llm-pref/lib/python3.10/site-packages/alpaca_eval/annotators/base.py", line 295, in _annotate
curr_annotated = self.annotators[annotator](
File "/anaconda3/envs/llm-pref/lib/python3.10/site-packages/alpaca_eval/annotators/base.py", line 665, in call
completions = self.fn_completions(prompts=prompts, **self.completions_kwargs, **decoding_kwargs)
File "/anaconda3/envs/llm-pref/lib/python3.10/site-packages/alpaca_eval/decoders/openai.py", line 152, in openai_completions
completions = list(
File "/anaconda3/envs/llm-pref/lib/python3.10/site-packages/tqdm/std.py", line 1181, in iter
for obj in iterable:
File "/anaconda3/envs/llm-pref/lib/python3.10/multiprocessing/pool.py", line 861, in next
self._cond.wait(timeout)
File "/anaconda3/envs/llm-pref/lib/python3.10/threading.py", line 320, in wait
waiter.acquire()
KeyboardInterrupt

**Comment by YannDubs** [comment]
Thanks for raising that issue @syleedandekar. Unfortunately, there's not much we can do about it given that OpenAI removed `davinci-003`. To keep the codebase usable I'll switch the annotators to the default [AlpacaEval](https://github.com/tatsu-lab/alpaca_eval), the numbers won't be exactly comparable to the ones in the paper unfortunately. In particular, it will use a single annotator rather than a batch of annotators. 

I'll do that before the end of the week-end. Until then you can probably change this line `https://github.com/tatsu-lab/alpaca_farm/blob/b17d605a360fc2936cbe6ee89e81d7270b440903/src/alpaca_farm/auto_annotations/eval.py#L163C13-L163C98` to be `"greedy_gpt4"`.

**Comment by syleedandekar** [comment]
I think the "greedy_gpt4" model is also deprecated

**Comment by YannDubs** [comment]
If you change this line https://github.com/tatsu-lab/alpaca_farm/blob/b17d605a360fc2936cbe6ee89e81d7270b440903/src/alpaca_farm/auto_annotations/annotators/greedy_gpt4/configs.yaml#L9C5-L9C29 to "gpt-4" it should work. I'll do a full fix before the end of the week, namely using the default AlpacaEval.
